import { PipelineContext, TestResult } from '../../types';
import { GitHubClient } from '../../utils/github';
import { Logger } from '../../utils/logger';

interface ReportSection {
  title: string;
  content: string;
}

export class PrCommenter {
  private github: GitHubClient;
  private logger = new Logger('PrCommenter');

  constructor(githubClient: GitHubClient) {
    this.github = githubClient;
  }

  generateReport(context: PipelineContext): string {
    const results = context.testResults || [];
    const passed = results.filter((r) => r.status === 'pass');
    const failed = results.filter((r) => r.status === 'fail');
    const warned = results.filter((r) => r.status === 'warn');

    const sections: ReportSection[] = [];

    sections.push({
      title: 'Summary',
      content: this.buildSummaryTable(passed.length, failed.length, warned.length, results),
    });

    if (failed.length > 0) {
      sections.push({
        title: 'Failed Tests',
        content: this.buildFailedSection(failed),
      });
    }

    if (warned.length > 0) {
      sections.push({
        title: 'Warnings',
        content: this.buildWarningsSection(warned),
      });
    }

    const perfData = context.logs.filter((l) => l.startsWith('[perf]'));
    if (perfData.length > 0) {
      sections.push({
        title: 'Performance Metrics',
        content: perfData.map((l) => `- ${l.replace('[perf] ', '')}`).join('\n'),
      });
    }

    if (passed.length > 0) {
      sections.push({
        title: 'Passing Tests',
        content: this.buildPassingSection(passed),
      });
    }

    return this.assembleReport(sections);
  }

  private buildSummaryTable(pass: number, fail: number, warn: number, results: TestResult[]): string {
    const total = pass + fail + warn;
    const avgDuration = total > 0 ? (results.reduce((sum, r) => sum + r.duration, 0) / total / 1000).toFixed(1) : '0';
    const statusIcon = fail > 0 ? '🔴' : warn > 0 ? '🟡' : '🟢';
    const devices = [...new Set(results.map((r) => r.device))];

    return [
      `| Metric | Value |`,
      `|--------|-------|`,
      `| Status | ${statusIcon} ${fail > 0 ? 'FAILED' : warn > 0 ? 'WARNING' : 'PASSED'} |`,
      `| Total Tests | ${total} |`,
      `| Passed | ${pass} |`,
      `| Failed | ${fail} |`,
      `| Warnings | ${warn} |`,
      `| Avg Duration | ${avgDuration}s |`,
      `| Devices | ${devices.join(', ') || 'N/A'} |`,
    ].join('\n');
  }

  private buildFailedSection(failed: TestResult[]): string {
    return failed
      .map((t) => {
        const lines = [
          `#### ${t.scenario}`,
          `- **Device**: ${t.device}`,
          `- **Duration**: ${(t.duration / 1000).toFixed(1)}s`,
          `- **Error**: \`${t.error || 'Unknown error'}\``,
        ];
        if (t.screenshot) {
          lines.push(`- **Screenshot**: ![failure](${t.screenshot})`);
        }
        return lines.join('\n');
      })
      .join('\n\n---\n\n');
  }

  private buildWarningsSection(warned: TestResult[]): string {
    return warned
      .map((t) => `- **${t.scenario}** on ${t.device}: ${t.error || 'Non-critical issue detected'}`)
      .join('\n');
  }

  private buildPassingSection(passed: TestResult[]): string {
    const rows = passed.map((t) => `| ${t.scenario} | ${t.device} | ${(t.duration / 1000).toFixed(1)}s |`).join('\n');

    return [
      '<details>',
      '<summary>View passing tests</summary>',
      '',
      '| Scenario | Device | Duration |',
      '|----------|--------|----------|',
      rows,
      '',
      '</details>',
    ].join('\n');
  }

  private assembleReport(sections: ReportSection[]): string {
    const header = '## Automated Testing Bot Report\n';
    const body = sections.map((s) => `### ${s.title}\n\n${s.content}`).join('\n\n');
    const footer = '\n\n---\n*Generated by Automated Testing Bot*';
    return header + '\n' + body + footer;
  }

  async postReport(owner: string, repo: string, prNumber: number, report: string): Promise<void> {
    try {
      await this.github.postComment(owner, repo, prNumber, report);
      this.logger.log('Report posted to PR', { prNumber });
    } catch (err) {
      this.logger.error('Failed to post report', err);
      throw err;
    }
  }
}
