import axios from 'axios';
import * as jwt from 'jsonwebtoken';
import { Logger } from './logger';

const logger = new Logger('GitHubClient');

interface GitHubAppConfig {
  appId: string;
  privateKey: string;
  installationId?: string;
}

function generateJWT(appId: string, privateKey: string): string {
  const now = Math.floor(Date.now() / 1000);
  const payload = {
    iat: now - 60, // issued 60s ago to account for clock drift
    exp: now + 10 * 60, // expires in 10 minutes
    iss: appId,
  };
  return jwt.sign(payload, privateKey, { algorithm: 'RS256' });
}

async function getInstallationToken(appId: string, privateKey: string, installationId?: string): Promise<string> {
  const jwtToken = generateJWT(appId, privateKey);
  const baseUrl = 'https://api.github.com';

  // If no installation ID provided, get the first one
  if (!installationId) {
    const res = await axios.get(`${baseUrl}/app/installations`, {
      headers: { Authorization: `Bearer ${jwtToken}`, Accept: 'application/vnd.github+json' },
    });
    if (!res.data.length) throw new Error('No GitHub App installations found');
    installationId = res.data[0].id;
  }

  const res = await axios.post(
    `${baseUrl}/app/installations/${installationId}/access_tokens`,
    {},
    { headers: { Authorization: `Bearer ${jwtToken}`, Accept: 'application/vnd.github+json' } },
  );

  return res.data.token;
}

export class GitHubClient {
  private token: string | null = null;
  private appConfig: GitHubAppConfig | null = null;
  private tokenExpiresAt: number = 0;
  private baseUrl = 'https://api.github.com';

  constructor(tokenOrAppId?: string, privateKey?: string, installationId?: string) {
    if (privateKey) {
      // GitHub App mode
      this.appConfig = {
        appId: tokenOrAppId || process.env.GITHUB_APP_ID || '',
        privateKey,
        installationId: installationId || process.env.GITHUB_APP_INSTALLATION_ID,
      };
    } else if (tokenOrAppId) {
      // Legacy PAT mode (for backwards compat)
      this.token = tokenOrAppId;
    } else {
      // Auto-detect from env
      const appId = process.env.GITHUB_APP_ID;
      const pk = process.env.GITHUB_APP_PRIVATE_KEY?.replace(/\\n/g, '\n');
      if (appId && pk) {
        this.appConfig = {
          appId,
          privateKey: pk,
          installationId: process.env.GITHUB_APP_INSTALLATION_ID,
        };
      } else {
        this.token = process.env.GITHUB_TOKEN || '';
      }
    }
  }

  private async getToken(): Promise<string> {
    // If using GitHub App, generate/refresh installation token
    if (this.appConfig) {
      const now = Date.now();
      if (!this.token || now >= this.tokenExpiresAt) {
        logger.log('Generating new GitHub App installation token');
        this.token = await getInstallationToken(
          this.appConfig.appId,
          this.appConfig.privateKey,
          this.appConfig.installationId,
        );
        this.tokenExpiresAt = now + 55 * 60 * 1000; // refresh 5 min before 1hr expiry
      }
    }
    return this.token || '';
  }

  private async headers(): Promise<Record<string, string>> {
    const token = await this.getToken();
    return {
      Authorization: `token ${token}`,
      Accept: 'application/vnd.github+json',
    };
  }

  async getPR(owner: string, repo: string, prNumber: number): Promise<any> {
    const url = `${this.baseUrl}/repos/${owner}/${repo}/pulls/${prNumber}`;
    const res = await axios.get(url, { headers: await this.headers() });
    return res.data;
  }

  async postComment(owner: string, repo: string, prNumber: number, body: string): Promise<void> {
    const headers = await this.headers();

    // Find existing bot comment to update instead of creating duplicate
    const existingId = await this.findBotComment(owner, repo, prNumber);
    if (existingId) {
      const url = `${this.baseUrl}/repos/${owner}/${repo}/issues/comments/${existingId}`;
      await axios.patch(url, { body }, { headers });
      return;
    }

    const url = `${this.baseUrl}/repos/${owner}/${repo}/issues/${prNumber}/comments`;
    await axios.post(url, { body }, { headers });
  }

  private async findBotComment(owner: string, repo: string, prNumber: number): Promise<number | null> {
    try {
      const url = `${this.baseUrl}/repos/${owner}/${repo}/issues/${prNumber}/comments?per_page=100`;
      const res = await axios.get(url, { headers: await this.headers() });
      const botComment = res.data.find(
        (c: any) => c.body?.includes('Automated Testing Bot Report') && c.body?.includes('Generated by Automated Testing Bot'),
      );
      return botComment?.id || null;
    } catch {
      return null;
    }
  }

  async addLabel(owner: string, repo: string, prNumber: number, labels: string[]): Promise<void> {
    const url = `${this.baseUrl}/repos/${owner}/${repo}/issues/${prNumber}/labels`;
    await axios.post(url, labels, { headers: await this.headers() });
  }

  async createIssue(owner: string, repo: string, title: string, body: string): Promise<any> {
    const url = `${this.baseUrl}/repos/${owner}/${repo}/issues`;
    const res = await axios.post(url, { title, body }, { headers: await this.headers() });
    return res.data;
  }

  async createCheckRun(
    owner: string,
    repo: string,
    headSha: string,
    name: string,
    conclusion: 'success' | 'failure' | 'neutral',
    output: { title: string; summary: string },
  ): Promise<any> {
    const url = `${this.baseUrl}/repos/${owner}/${repo}/check-runs`;
    const res = await axios.post(
      url,
      { name, head_sha: headSha, status: 'completed', conclusion, output },
      { headers: await this.headers() },
    );
    return res.data;
  }
}
