import { PipelineContext, ModuleResult, TestResult } from '../../types';
import { runMaestro, MaestroBuildTimeoutError } from './maestro-runner';
import { getDevicesForPlatform, getMinimalDeviceSet } from './device-matrix';
import { Logger } from '../../utils/logger';

const logger = new Logger('BrowserStack');

// Maestro-only execution path. The legacy Appium TestExecutor has been
// retired from the production pipeline; element resolution + retries now run
// inside Maestro on BrowserStack (server-side) instead of in our process.
// See features/maestro/*.yaml for the flows submitted to each build.
export async function runBrowserStack(context: PipelineContext): Promise<ModuleResult> {
  try {
    const flows = context.maestroFlows ?? [];
    if (flows.length === 0) {
      return {
        moduleName: 'BrowserStack',
        status: 'warning',
        error: 'No Maestro flows generated by TestWriter — nothing to execute',
      };
    }

    const androidAppUrl = context.appBuild?.androidAppUrl;
    const iosAppUrl = context.appBuild?.iosAppUrl;
    if (!androidAppUrl && !iosAppUrl) {
      return {
        moduleName: 'BrowserStack',
        status: 'error',
        error: 'No app URLs available. App build may have failed.',
      };
    }

    const framework = context.codeAnalysis?.framework;
    const hasAndroid = !!androidAppUrl;
    const hasIos = !!iosAppUrl;
    const platform: 'android' | 'ios' | 'both' =
      framework === 'swift' ? 'ios' :
      framework === 'kotlin' ? 'android' :
      hasAndroid && hasIos ? 'both' :
      hasAndroid ? 'android' :
      hasIos ? 'ios' :
      'both';

    const isReleaseBranch = context.branch.startsWith('release/') || context.branch === 'main';
    const devices = isReleaseBranch ? getDevicesForPlatform(platform) : getMinimalDeviceSet();

    const minIosVersion = context.codeAnalysis?.minIosVersion;
    const androidDevices = devices.filter((d) => d.platform === 'Android');
    const iosDevices = devices.filter((d) => {
      if (d.platform !== 'iOS') return false;
      if (minIosVersion && parseFloat(d.os_version) < parseFloat(minIosVersion)) {
        logger.warn(`Skipping ${d.name} (iOS ${d.os_version}) — app requires iOS ${minIosVersion}+`);
        return false;
      }
      return true;
    });

    logger.log('Maestro execution plan', {
      flows: flows.length,
      androidDevices: androidDevices.map((d) => d.name),
      iosDevices: iosDevices.map((d) => d.name),
      isReleaseBranch,
    });

    const results: TestResult[] = await runMaestro({
      androidAppUrl,
      iosAppUrl,
      flows,
      androidDevices,
      iosDevices,
      project: 'AutomatedTestingBot',
      buildName: `PR-${context.prNumber}-${Date.now()}`,
    });

    if (results.length === 0) {
      logger.warn('No Maestro test results returned', {
        iosDevices: iosDevices.length,
        androidDevices: androidDevices.length,
        minIosVersion,
      });
      return { moduleName: 'BrowserStack', status: 'warning', error: 'No compatible devices available for testing' };
    }

    context.testResults = results;

    const passed = results.filter((r) => r.status === 'pass').length;
    const failed = results.filter((r) => r.status === 'fail').length;
    const warned = results.filter((r) => r.status === 'warn').length;
    const total = results.length;
    const passRate = total > 0 ? Math.round((passed / total) * 100) : 0;

    logger.log('Maestro execution complete', { total, passed, failed, warned, passRate });

    return {
      moduleName: 'BrowserStack',
      status: failed > 0 ? 'warning' : 'success',
      data: {
        results,
        summary: { total, passed, failed, warned, passRate },
        devices: devices.map((d) => d.name),
      },
    };
  } catch (error) {
    logger.error('BrowserStack module failed', error);
    // Let the timeout error escape with its type intact so runWithRetry can
    // recognize it (instanceof check) and skip retrying. Wrapping it in a
    // plain ModuleResult here would lose the class and trigger an orphan loop.
    if (error instanceof MaestroBuildTimeoutError) throw error;
    return { moduleName: 'BrowserStack', status: 'error', error: String(error) };
  }
}
